services:
  prism:
    image: stoplight/prism:latest
    container_name: library_prism_mock
    ports:
      - "4010:4010"
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml
    command: mock -h 0.0.0.0 -m false /tmp/openapi.yaml