services:
  db:
    image: postgres:15
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: book-cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: library_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@db:5432/library"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
    volumes:
      - .:/code

volumes:
  postgres_data: